name: ephemeral_ec2_run-this
on: 
  workflow_call:
    inputs:
      run-this:
        required: true
        type: string
      arch:
        required: false
        type: string
        default: x86_64
      artifact-path:
        required: false
        type: string
        default: ''
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: [self-hosted, lightsail]
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: AllStarLink/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: AllStarLink/ec2-github-runner@aslv2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ${{ inputs.arch == 'x86_64' && vars.EC2_AMI_AMD64 || inputs.arch == 'arm64' && vars.EC2_AMI_ARM64  || null }}
          ec2-instance-type: ${{ inputs.arch == 'x86_64' && vars.EC2_BUILD_INST_TYPE_AMD64 || inputs.arch == 'arm64' && vars.EC2_BUILD_INST_TYPE_AMD64 || null }}
          subnet-id: ${{ vars.EC2_SUBNET_ID }}
          security-group-id: ${{ vars.EC2_SECGRP_ID }}
#  configure-runner:
#    name: Set the runner up
#    needs: start-runner
#    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
#    steps:
#      - name: Set DNS Server
#        run: echo "nameserver 172.26.47.97" > /etc/resolv.conf
  do-the-job:
    name: Do the job on the runner
    needs:
      - start-runner # required to start the main job when the runner is ready
 #     - configure-runner
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps: 
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Run This
        run: ${{ inputs.run-this }}
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          APTLY_API_USER: ${{ secrets.APTLY_API_USER }}
          APTLY_API_PASS: ${{ secrets.APTLY_API_PASS }}
          APTLY_GPG_PASSPHRASE: ${{ secrets.APTLY_GPG_PASSPHRASE }}
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    runs-on: [self-hosted, lightsail]
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: AllStarLink/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Stop EC2 runner
        uses: AllStarLink/ec2-github-runner@aslv2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
